#!/usr/bin/env python3

import os
from inky import InkyPHAT
from PIL import Image

PATH = os.path.dirname(__file__)

inky_display = InkyPHAT("yellow")
inky_display.set_border(inky_display.WHITE)

img = Image.open(os.path.join(PATH, "assets/display-off.png"))

pal_img = Image.new("P", (1, 1))
pal_img.putpalette((255, 255, 255, 0, 0, 0, 0, 255, 0) + (0, 0, 0) * 252)

img = img.convert("RGB").quantize(palette=pal_img)

inky_display.set_image(img)
inky_display.show()
